# Advanced Transire configuration with function grouping
name: full-app
language: go
cloud: aws
runtime: lambda
iac: cdk
ci: github

# Lambda function configuration defaults
lambda:
  architecture: arm64
  timeout_seconds: 30
  memory_mb: 128

# Multiple functions with specific configurations
functions:
  # Web function handles all HTTP traffic
  web:
    include:
      - http_handlers: "*"
    memory_mb: 512
    timeout_seconds: 30
    environment:
      FUNCTION_TYPE: web

  # Background function handles async work
  background:
    include:
      - queue_handlers: "*"
      - schedule_handlers: "*"
    memory_mb: 1024
    timeout_seconds: 300
    environment:
      FUNCTION_TYPE: background

  # Critical function for high-priority queues
  critical:
    include:
      - queue_handlers: ["payment-queue", "order-queue"]
    memory_mb: 2048
    timeout_seconds: 60
    reserved_concurrency: 50
    environment:
      FUNCTION_TYPE: critical

# Global environment variables
environment:
  LOG_LEVEL: info
  SERVICE_NAME: full-app
  NODE_ENV: production
  DATABASE_URL: ${DATABASE_URL}
  REDIS_URL: ${REDIS_URL}
  API_KEY: !Ref ApiKeySecret

# VPC configuration for database access
vpc:
  subnet_ids:
    - subnet-12345678
    - subnet-87654321
  security_group_ids:
    - sg-abcdef123456

# Reference existing AWS resources
existing_resources:
  dynamodb_tables:
    - name: users-table
      arn: "arn:aws:dynamodb:us-east-1:123456789012:table/users"
      permissions: ["read", "write"]
    - name: orders-table
      arn: "arn:aws:dynamodb:us-east-1:123456789012:table/orders"
      permissions: ["read", "write"]
  s3_buckets:
    - name: uploads-bucket
      arn: "arn:aws:s3:::my-app-uploads-bucket"
      permissions: ["read", "write"]
    - name: static-assets-bucket
      arn: "arn:aws:s3:::my-app-static-assets"
      permissions: ["read"]
  secrets:
    - name: api-key
      arn: "arn:aws:secretsmanager:us-east-1:123456789012:secret:api-key-abc123"
    - name: database-credentials
      arn: "arn:aws:secretsmanager:us-east-1:123456789012:secret:db-credentials-def456"

# Queue-specific configuration
queues:
  # High-priority queues
  payment-queue:
    visibility_timeout_seconds: 60
    max_receive_count: 3
    batch_size: 1  # Process payments one at a time
    fifo: true
  order-queue:
    visibility_timeout_seconds: 45
    max_receive_count: 3
    batch_size: 5
    fifo: true

  # Standard queues
  email-queue:
    visibility_timeout_seconds: 30
    max_receive_count: 5
    batch_size: 10
  notification-queue:
    visibility_timeout_seconds: 30
    max_receive_count: 3
    batch_size: 10
  analytics-queue:
    visibility_timeout_seconds: 120
    max_receive_count: 2
    batch_size: 25

# Schedule-specific configuration
schedules:
  # Daily tasks
  daily-cleanup:
    timezone: "America/New_York"
    enabled: true
    timeout_seconds: 900  # 15 minutes
  daily-reports:
    timezone: "UTC"
    enabled: true
    timeout_seconds: 600  # 10 minutes

  # Hourly tasks
  hourly-metrics:
    timezone: "UTC"
    enabled: true
    timeout_seconds: 300  # 5 minutes
  hourly-sync:
    timezone: "UTC"
    enabled: false  # Disabled for now

# CDK extensions for custom resources
cdk_extensions:
  - file: "extensions/database.ts"
  - file: "extensions/monitoring.ts"
  - file: "extensions/alarms.ts"
  - file: "extensions/api-domain.ts"

# Development settings
development:
  http_port: 3000
  queue_port: 4000
  scheduler_port: 5000
  auto_reload: true
  log_level: debug
  mock_aws_services: true